version: "3"

services:
    back:
        build:
            context: ./back/
        env_file:
            - ./back/.env
        ports:
            - "4000:4000"
        depends_on:
            - db
        networks:
            - private
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - private
    front:
        networks:
            - private
        build:
            context: ./front/
        ports:
            - "3000:3000"
volumes:
    pgdata:

networks:
    private:
